/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 ./public/models/Map.glb -o ./src/components/models/Map.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Map(props) {
  const { nodes, materials } = useGLTF('models/Map.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Tree01A.geometry} material={materials.Vegetation} position={[12.397, 0, -14.411]} scale={0.01} />
      <mesh geometry={nodes.Tree04A.geometry} material={materials.Vegetation} position={[3.958, 0, -8.006]} scale={0.01} />
      <mesh geometry={nodes.Tree02A.geometry} material={materials.Vegetation} position={[6.556, 0, 14.122]} scale={0.01} />
      <mesh geometry={nodes.Tree03B.geometry} material={materials.Vegetation} position={[6.723, 0, -1.925]} scale={0.01} />
      <mesh geometry={nodes.Tree05A.geometry} material={materials.Vegetation} position={[4.592, 0, -6.231]} scale={0.01} />
      <mesh geometry={nodes.Tree03A.geometry} material={materials.Vegetation} position={[14.283, 0, -8.63]} scale={0.01} />
      <mesh geometry={nodes.Tree01B.geometry} material={materials.Vegetation} position={[-7.299, 0, 11.976]} scale={0.01} />
      <mesh geometry={nodes.Tree02B.geometry} material={materials.Vegetation} position={[-12.862, 0, -2.95]} scale={0.01} />
      <mesh geometry={nodes.Tree05B.geometry} material={materials.Vegetation} position={[5.095, 0, -1.798]} scale={0.01} />
      <mesh geometry={nodes.Tree04B.geometry} material={materials.Vegetation} position={[8.733, 0, -0.539]} scale={0.01} />
      <mesh geometry={nodes.TreeTrunk01A.geometry} material={materials.Vegetation} position={[2.884, 0, -16.057]} scale={0.01} />
      <mesh geometry={nodes.TreeTrunk01C.geometry} material={materials.Vegetation} position={[2.373, 0, 11.412]} scale={0.01} />
      <mesh geometry={nodes.TreeTrunk01B.geometry} material={materials.Vegetation} position={[1.312, 0, -13.497]} scale={0.01} />
      <mesh geometry={nodes.Rock01A.geometry} material={materials.Stone} position={[-0.875, 0, 10.935]} scale={0.01} />
      <mesh geometry={nodes.Plane.geometry} material={materials.floor_material} scale={[20, 1, 20]} />
    </group>
  )
}

useGLTF.preload('models/Map.glb')
